/* global NexT, CONFIG, Velocity */
NexT.boot={},NexT.boot.registerEvents=function(){NexT.utils.registerScrollPercent(),NexT.utils.registerCanIUseTag();
// Mobile top menu bar.
var e=document.querySelector(".site-nav-toggle .toggle"),t=document.querySelector(".site-nav"),i=function(i){e.classList.toggle("toggle-close",i),t.classList.toggle("site-nav-on",i),document.body.classList.toggle("nav-open",i),e.setAttribute("aria-expanded",i?"true":"false")};e.addEventListener("click",(function(){i(!t.classList.contains("site-nav-on"))})),t.querySelectorAll("a").forEach((function(e){e.addEventListener("click",(function(){i(!1)}))})),document.addEventListener("keydown",(function(e){"Escape"===e.key&&t.classList.contains("site-nav-on")&&i(!1)}));document.querySelectorAll(".sidebar-nav li").forEach((e=>{e.addEventListener("click",(e=>{var t=e.currentTarget,i="sidebar-nav-active",o="sidebar-panel-active";if(!t.classList.contains(i)){var a=document.querySelectorAll(".sidebar-panel"),n=t.classList.contains("sidebar-nav-overview")?document.querySelector(".site-overview-wrap"):document.querySelector(".post-toc-wrap"),s=[...a].find((e=>e!==n));n&&s&&(window.anime.remove(a),window.anime({targets:s,duration:100,easing:"easeInOutSine",opacity:0,complete:()=>{
// Prevent adding TOC to Overview if Overview was selected when close & open sidebar.
s.classList.remove(o),n.style.opacity=0,n.classList.add(o),window.anime({targets:n,duration:100,easing:"easeInOutSine",opacity:1})}}),[...t.parentNode.children].forEach((e=>{e.classList.remove(i)})),t.classList.add(i))}}))})),window.addEventListener("resize",NexT.utils.initSidebarDimension),window.addEventListener("hashchange",(()=>{var e=location.hash;if(""!==e&&!e.match(/%\S{2}/)){var t=document.querySelector(`.tabs ul.nav-tabs li a[href="${e}"]`);t&&t.click()}}))},NexT.boot.refresh=function(){
/**
   * Register JS handlers by condition option.
   * Need to add config option in Front-End at 'layout/_partials/head.swig' file.
   */
CONFIG.fancybox&&NexT.utils.wrapImageWithFancyBox(),CONFIG.mediumzoom&&window.mediumZoom(".post-body :not(a) > img, .post-body > img"),CONFIG.lazyload&&window.lozad(".post-body img").observe(),CONFIG.pangu&&window.pangu.spacingPage(),CONFIG.exturl&&NexT.utils.registerExtURL(),CONFIG.copycode.enable&&NexT.utils.registerCopyCode(),NexT.utils.registerTabsTag(),NexT.utils.registerActiveMenuItem(),NexT.utils.registerLangSelect(),NexT.utils.registerSidebarTOC(),NexT.utils.wrapTableWithBox(),NexT.utils.registerVideoIframe()},NexT.boot.motion=function(){
// Define Motion Sequence & Bootstrap Motion.
CONFIG.motion.enable&&NexT.motion.integrator.add(NexT.motion.middleWares.logo).add(NexT.motion.middleWares.menu).add(NexT.motion.middleWares.postList).add(NexT.motion.middleWares.sidebar).bootstrap(),NexT.utils.updateSidebarPosition()},document.addEventListener("DOMContentLoaded",(()=>{NexT.boot.registerEvents(),NexT.boot.refresh(),NexT.boot.motion()}));