/* global NexT, CONFIG */
HTMLElement.prototype.wrap=function(e){this.parentNode.insertBefore(e,this),this.parentNode.removeChild(this),e.appendChild(this)},NexT.utils={
/**
   * Wrap images with fancybox.
   */
wrapImageWithFancyBox:function(){document.querySelectorAll(".post-body :not(a) > img, .post-body > img").forEach((e=>{var t=$(e),a=t.attr("data-src")||t.attr("src"),o=t.wrap(`<a class="fancybox fancybox.image" href="${a}" itemscope itemtype="http://schema.org/ImageObject" itemprop="url"></a>`).parent("a");t.is(".post-gallery img")?o.attr("data-fancybox","gallery").attr("rel","gallery"):t.is(".group-picture img")?o.attr("data-fancybox","group").attr("rel","group"):o.attr("data-fancybox","default").attr("rel","default");var n=t.attr("title")||t.attr("alt");n&&(o.append(`<p class="image-caption">${n}</p>`),
// Make sure img title tag will show correctly in fancybox
o.attr("title",n).attr("data-caption",n))})),$.fancybox.defaults.hash=!1,$(".fancybox").fancybox({loop:!0,helpers:{overlay:{locked:!1}}})},registerExtURL:function(){document.querySelectorAll("span.exturl").forEach((e=>{let t=document.createElement("a");
// https://stackoverflow.com/questions/30106476/using-javascripts-atob-to-decode-base64-doesnt-properly-decode-utf-8-strings
t.href=decodeURIComponent(atob(e.dataset.url).split("").map((e=>"%"+("00"+e.charCodeAt(0).toString(16)).slice(-2))).join("")),t.rel="noopener external nofollow noreferrer",t.target="_blank",t.className=e.className,t.title=e.title,t.innerHTML=e.innerHTML,e.parentNode.replaceChild(t,e)}))},
/**
   * One-click copy code support.
   */
registerCopyCode:function(){document.querySelectorAll("figure.highlight").forEach((e=>{const t=document.createElement("div");e.wrap(t),t.classList.add("highlight-container"),t.insertAdjacentHTML("beforeend",'<div class="copy-btn"><i class="fa fa-clipboard fa-fw"></i></div>');var a=e.parentNode.querySelector(".copy-btn");a.addEventListener("click",(e=>{var t=e.currentTarget,a=[...t.parentNode.querySelectorAll(".code .line")].map((e=>e.innerText)).join("\n"),o=document.createElement("textarea");o.style.top=window.scrollY+"px",// Prevent page scrolling
o.style.position="absolute",o.style.opacity="0",o.readOnly=!0,o.value=a,document.body.append(o);const n=document.getSelection(),r=n.rangeCount>0&&n.getRangeAt(0);o.select(),o.setSelectionRange(0,a.length),o.readOnly=!1;var i=document.execCommand("copy");CONFIG.copycode.show_result&&(t.querySelector("i").className=i?"fa fa-check fa-fw":"fa fa-times fa-fw"),o.blur(),// For iOS
t.blur(),r&&(n.removeAllRanges(),n.addRange(r)),document.body.removeChild(o)})),a.addEventListener("mouseleave",(e=>{setTimeout((()=>{e.target.querySelector("i").className="fa fa-clipboard fa-fw"}),300)}))}))},wrapTableWithBox:function(){document.querySelectorAll("table").forEach((e=>{const t=document.createElement("div");t.className="table-container",e.wrap(t)}))},registerVideoIframe:function(){document.querySelectorAll("iframe").forEach((e=>{if(["www.youtube.com","player.vimeo.com","player.youku.com","player.bilibili.com","www.tudou.com"].some((t=>e.src.includes(t)))&&!e.parentNode.matches(".video-container")){const t=document.createElement("div");t.className="video-container",e.wrap(t);let a=Number(e.width),o=Number(e.height);a&&o&&(e.parentNode.style.paddingTop=o/a*100+"%")}}))},registerScrollPercent:function(){var e=document.querySelector(".back-to-top"),t=document.querySelector(".reading-progress-bar");
// For init back to top in sidebar if page was scrolled after page refresh.
window.addEventListener("scroll",(()=>{if(e||t){var a=document.querySelector(".container").offsetHeight,o=window.innerHeight,n=a>o?a-o:document.body.scrollHeight-o,r=Math.min(100*window.scrollY/n,100);e&&(e.classList.toggle("back-to-top-on",window.scrollY>50),e.querySelector("span").innerText=Math.round(r)+"%"),t&&(t.style.width=r.toFixed(2)+"%")}})),e&&e.addEventListener("click",(()=>{var e=Math.abs(window.scrollY),t=Math.min(560,300+.055*e);window.anime.remove(document.scrollingElement),window.anime({targets:document.scrollingElement,duration:t,easing:"easeInOutQuart",scrollTop:0})}))},
/**
   * Tabs tag listener (without twitter bootstrap).
   */
registerTabsTag:function(){
// Binding `nav-tabs` & `tab-content` by real time permalink changing.
document.querySelectorAll(".tabs ul.nav-tabs .tab").forEach((e=>{e.addEventListener("click",(e=>{e.preventDefault();var t=e.currentTarget;
// Prevent selected tab to select again.
if(!t.classList.contains("active")){
// Add & Remove active class on `nav-tabs` & `tab-content`.
[...t.parentNode.children].forEach((e=>{e.classList.remove("active")})),t.classList.add("active");var a=document.getElementById(t.querySelector("a").getAttribute("href").replace("#",""));[...a.parentNode.children].forEach((e=>{e.classList.remove("active")})),a.classList.add("active"),
// Trigger event
a.dispatchEvent(new Event("tabs:click",{bubbles:!0}))}}))})),window.dispatchEvent(new Event("tabs:register"))},registerCanIUseTag:function(){
// Get responsive height passed from iframe.
window.addEventListener("message",(({data:e})=>{if("string"==typeof e&&e.includes("ciu_embed")){var t=e.split(":")[1],a=e.split(":")[2];document.querySelector(`iframe[data-feature=${t}]`).style.height=parseInt(a,10)+5+"px"}}),!1)},registerActiveMenuItem:function(){document.querySelectorAll(".menu-item").forEach((e=>{var t=e.querySelector("a[href]");if(t){var a=t.pathname===location.pathname||t.pathname===location.pathname.replace("index.html",""),o=!CONFIG.root.startsWith(t.pathname)&&location.pathname.startsWith(t.pathname);e.classList.toggle("menu-item-active",t.hostname===location.hostname&&(a||o))}}))},registerLangSelect:function(){document.querySelectorAll(".lang-select").forEach((e=>{e.value=CONFIG.page.lang,e.addEventListener("change",(()=>{let t=e.options[e.selectedIndex];document.querySelectorAll(".lang-select-label span").forEach((e=>e.innerText=t.text));let a=t.dataset.href;window.pjax?window.pjax.loadUrl(a):window.location.href=a}))}))},registerSidebarTOC:function(){const e=document.querySelectorAll(".post-toc li"),t=e=>{const t=e.querySelector(".nav-text");if(!t)return;if(!t.dataset.marqueeReady){const e=t.textContent.trim();t.textContent="";const a=document.createElement("span");a.className="toc-marquee-track";const o=document.createElement("span");o.textContent=e;const n=document.createElement("span");n.className="toc-marquee-gap",n.setAttribute("aria-hidden","true");const r=document.createElement("span");r.className="toc-marquee-copy",r.textContent=e,a.append(o,n,r),t.appendChild(a),t.dataset.marqueeReady="true"}const a=t.querySelector(".toc-marquee-track"),o=a.children[0],n=a.querySelector(".toc-marquee-gap");e.classList.remove("toc-title-overflow"),a.style.removeProperty("--toc-scroll-distance"),a.style.removeProperty("--toc-marquee-duration");const r=o.scrollWidth-t.clientWidth;r>2&&(e.classList.add("toc-title-overflow"),requestAnimationFrame((()=>{const e=o.offsetWidth+n.offsetWidth;a.style.setProperty("--toc-scroll-distance",`-${e}px`),a.style.setProperty("--toc-marquee-duration",`${Math.min(5,Math.max(2.2,2.2+.01*r))}s`)})))},a=document.querySelectorAll(".post-toc .nav-link");a.forEach((e=>{e.addEventListener("mouseenter",(()=>t(e)))})),window.addEventListener("resize",(()=>{a.forEach(t)}));const o=[...e].map((e=>{var t=e.querySelector("a.nav-link"),a=document.getElementById(decodeURI(t.getAttribute("href")).replace("#",""));
// TOC item animation navigate.
return t.addEventListener("click",(e=>{e.preventDefault();var t=a.getBoundingClientRect().top+window.scrollY,o=Math.abs(t+10-window.scrollY),n=Math.min(560,300+.055*o);window.anime.remove(document.scrollingElement),window.anime({targets:document.scrollingElement,duration:n,easing:"easeInOutQuart",scrollTop:t+10})})),a}));var n=document.querySelector(".post-toc-wrap");!function t(a){a=Math.floor(a+1e4);let r=new IntersectionObserver(((r,i)=>{let c=document.documentElement.scrollHeight+100;if(c>a)return i.disconnect(),void t(c);let s=function(e){let t=0,a=e[t];if(a.boundingClientRect.top>0)return t=o.indexOf(a.target),0===t?0:t-1;for(;t<e.length;t++){if(!(e[t].boundingClientRect.top<=0))return o.indexOf(a.target);a=e[t]}return o.indexOf(a.target)}(r);!function(e){if(!e.classList.contains("active-current")){document.querySelectorAll(".post-toc .active").forEach((e=>{e.classList.remove("active","active-current")})),e.classList.add("active","active-current");for(var t=e.parentNode;!t.matches(".post-toc");)t.matches("li")&&t.classList.add("active"),t=t.parentNode;
// Scrolling to center active TOC element if TOC content is taller then viewport.
window.anime({targets:n,duration:180,easing:"linear",scrollTop:n.scrollTop-n.offsetHeight/2+e.getBoundingClientRect().top-n.getBoundingClientRect().top})}}(e[s])}),{rootMargin:a+"px 0px -100% 0px",threshold:0});o.forEach((e=>{e&&r.observe(e)}))}(document.documentElement.scrollHeight)},hasMobileUA:function(){let e=navigator.userAgent;return/iPad|iPhone|Android|Opera Mini|BlackBerry|webOS|UCWEB|Blazer|PSP|IEMobile|Symbian/g.test(e)},isTablet:function(){return window.screen.width<992&&window.screen.width>767&&this.hasMobileUA()},isMobile:function(){return window.screen.width<767&&this.hasMobileUA()},isDesktop:function(){return!this.isTablet()&&!this.isMobile()},supportsPDFs:function(){let e=navigator.userAgent,t=e.includes("irefox")&&parseInt(e.split("rv:")[1].split(".")[0],10)>18,a=void 0!==navigator.mimeTypes["application/pdf"],o=/iphone|ipad|ipod/i.test(e.toLowerCase());return t||a&&!o},
/**
   * Init Sidebar & TOC inner dimensions on all pages and for all schemes.
   * Need for Sidebar/TOC inner scrolling if content taller then viewport.
   */
initSidebarDimension:function(){var e=document.querySelector(".sidebar-nav"),t="none"!==e.style.display?e.offsetHeight:0,a=CONFIG.sidebar.offset||12,o=CONFIG.back2top.enable&&CONFIG.back2top.sidebar?document.querySelector(".back-to-top").offsetHeight:0,n=2*CONFIG.sidebar.padding+t+o;
// Margin of sidebar b2t: -4px -10px -18px, brings a different of 22px.
"Pisces"!==CONFIG.scheme&&"Gemini"!==CONFIG.scheme||(n+=2*a-22);
// Initialize Sidebar & TOC Height.
var r=document.body.offsetHeight-n+"px";document.querySelector(".site-overview-wrap").style.maxHeight=r,document.querySelector(".post-toc-wrap").style.maxHeight=r},updateSidebarPosition:function(){var e=document.querySelector(".sidebar-nav"),t=document.querySelector(".post-toc");if(t?(e.style.display="",e.classList.add("motion-element"),document.querySelector(".sidebar-nav-toc").click()):(e.style.display="none",e.classList.remove("motion-element"),document.querySelector(".sidebar-nav-overview").click()),NexT.utils.initSidebarDimension(),this.isDesktop()&&"Pisces"!==CONFIG.scheme&&"Gemini"!==CONFIG.scheme){
// Expand sidebar on post detail page by default, when post has a toc.
var a=CONFIG.page.sidebar;"boolean"!=typeof a&&(
// There's no definition sidebar in the page front-matter.
a="always"===CONFIG.sidebar.display||"post"===CONFIG.sidebar.display&&t),a&&window.dispatchEvent(new Event("sidebar:show"))}},getScript:function(e,t,a){if(a)t();else{var o=document.createElement("script");o.onload=o.onreadystatechange=function(e,a){(a||!o.readyState||/loaded|complete/.test(o.readyState))&&(o.onload=o.onreadystatechange=null,o=void 0,!a&&t&&setTimeout(t,0))},o.src=e,document.head.appendChild(o)}},loadComments:function(e,t){if(!CONFIG.comments.lazyload||!e)return void t();let a=new IntersectionObserver(((e,a)=>{e[0].isIntersecting&&(t(),a.disconnect())}));return a.observe(e),a}};